### ISSUE TITLE
ZCertificate does not recognize the extension "Netscape Cert Type"

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [zmap/zcertificate#14]
ZCertificate does not recognize the extension "Netscape Cert Type"
[cert-example-ie-cer01.zip](https://github.com/zmap/zcertificate/files/4600000/cert-example-ie-cer01.zip)

**Comment by zakird** [comment]
Hi @GOODPWDCETCSZ,
This is not the right project to be creating these issues in. This parsing takes place in https://github.com/zmap/zcrypto. If you can submit PRs to help parse these types of fields, we're happy to merge them, but to be very blunt, these types of issues aren't going to be fixed by the core team based on time constraints in the near term. There are many more pressing issues like getting TLS merged in.

**Comment by cpu** [comment]
Closing as WONTFIX.
